# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: exchange_rates.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='exchange_rates.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\n\023bank.exchange_rates'),
  serialized_pb=_b('\n\x14\x65xchange_rates.proto\"i\n\nCurrencies\x12\'\n\x05names\x18\x01 \x03(\x0e\x32\x18.Currencies.CurrencyName\"2\n\x0c\x43urrencyName\x12\x07\n\x03\x45UR\x10\x00\x12\x07\n\x03USD\x10\x01\x12\x07\n\x03GBP\x10\x02\x12\x07\n\x03\x43HF\x10\x03\",\n\x0cMonetaryType\x12\r\n\x05units\x18\x01 \x01(\x03\x12\r\n\x05\x63\x65nts\x18\x02 \x01(\x05\"a\n\x04Rate\x12\x1d\n\x04rate\x18\x01 \x03(\x0b\x32\x0f.Rate.RateEntry\x1a:\n\tRateEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.MonetaryType:\x02\x38\x01\"\n\n\x08NoParams2Y\n\x0c\x45xchangeRate\x12\"\n\x08GetRates\x12\x0b.Currencies\x1a\x05.Rate\"\x00\x30\x01\x12%\n\x07GetTest\x12\t.NoParams\x1a\r.MonetaryType\"\x00\x42\x15\n\x13\x62\x61nk.exchange_ratesb\x06proto3')
)



_CURRENCIES_CURRENCYNAME = _descriptor.EnumDescriptor(
  name='CurrencyName',
  full_name='Currencies.CurrencyName',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EUR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USD', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='GBP', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CHF', index=3, number=3,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=79,
  serialized_end=129,
)
_sym_db.RegisterEnumDescriptor(_CURRENCIES_CURRENCYNAME)


_CURRENCIES = _descriptor.Descriptor(
  name='Currencies',
  full_name='Currencies',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='Currencies.names', index=0,
      number=1, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CURRENCIES_CURRENCYNAME,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=129,
)


_MONETARYTYPE = _descriptor.Descriptor(
  name='MonetaryType',
  full_name='MonetaryType',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='units', full_name='MonetaryType.units', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cents', full_name='MonetaryType.cents', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=175,
)


_RATE_RATEENTRY = _descriptor.Descriptor(
  name='RateEntry',
  full_name='Rate.RateEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Rate.RateEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Rate.RateEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=216,
  serialized_end=274,
)

_RATE = _descriptor.Descriptor(
  name='Rate',
  full_name='Rate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='rate', full_name='Rate.rate', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RATE_RATEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=177,
  serialized_end=274,
)


_NOPARAMS = _descriptor.Descriptor(
  name='NoParams',
  full_name='NoParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=286,
)

_CURRENCIES.fields_by_name['names'].enum_type = _CURRENCIES_CURRENCYNAME
_CURRENCIES_CURRENCYNAME.containing_type = _CURRENCIES
_RATE_RATEENTRY.fields_by_name['value'].message_type = _MONETARYTYPE
_RATE_RATEENTRY.containing_type = _RATE
_RATE.fields_by_name['rate'].message_type = _RATE_RATEENTRY
DESCRIPTOR.message_types_by_name['Currencies'] = _CURRENCIES
DESCRIPTOR.message_types_by_name['MonetaryType'] = _MONETARYTYPE
DESCRIPTOR.message_types_by_name['Rate'] = _RATE
DESCRIPTOR.message_types_by_name['NoParams'] = _NOPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Currencies = _reflection.GeneratedProtocolMessageType('Currencies', (_message.Message,), dict(
  DESCRIPTOR = _CURRENCIES,
  __module__ = 'exchange_rates_pb2'
  # @@protoc_insertion_point(class_scope:Currencies)
  ))
_sym_db.RegisterMessage(Currencies)

MonetaryType = _reflection.GeneratedProtocolMessageType('MonetaryType', (_message.Message,), dict(
  DESCRIPTOR = _MONETARYTYPE,
  __module__ = 'exchange_rates_pb2'
  # @@protoc_insertion_point(class_scope:MonetaryType)
  ))
_sym_db.RegisterMessage(MonetaryType)

Rate = _reflection.GeneratedProtocolMessageType('Rate', (_message.Message,), dict(

  RateEntry = _reflection.GeneratedProtocolMessageType('RateEntry', (_message.Message,), dict(
    DESCRIPTOR = _RATE_RATEENTRY,
    __module__ = 'exchange_rates_pb2'
    # @@protoc_insertion_point(class_scope:Rate.RateEntry)
    ))
  ,
  DESCRIPTOR = _RATE,
  __module__ = 'exchange_rates_pb2'
  # @@protoc_insertion_point(class_scope:Rate)
  ))
_sym_db.RegisterMessage(Rate)
_sym_db.RegisterMessage(Rate.RateEntry)

NoParams = _reflection.GeneratedProtocolMessageType('NoParams', (_message.Message,), dict(
  DESCRIPTOR = _NOPARAMS,
  __module__ = 'exchange_rates_pb2'
  # @@protoc_insertion_point(class_scope:NoParams)
  ))
_sym_db.RegisterMessage(NoParams)


DESCRIPTOR._options = None
_RATE_RATEENTRY._options = None

_EXCHANGERATE = _descriptor.ServiceDescriptor(
  name='ExchangeRate',
  full_name='ExchangeRate',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=288,
  serialized_end=377,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRates',
    full_name='ExchangeRate.GetRates',
    index=0,
    containing_service=None,
    input_type=_CURRENCIES,
    output_type=_RATE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetTest',
    full_name='ExchangeRate.GetTest',
    index=1,
    containing_service=None,
    input_type=_NOPARAMS,
    output_type=_MONETARYTYPE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_EXCHANGERATE)

DESCRIPTOR.services_by_name['ExchangeRate'] = _EXCHANGERATE

# @@protoc_insertion_point(module_scope)
